(deftheme bootstrap
  "Created 2022-06-22.")

(custom-theme-set-faces
 'bootstrap
 '(default ((t (:family "JetBrains Mono NL" :foundry "nil" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#839496" :background "#002b36" :stipple nil :inherit nil))))
 '(cursor ((((class color) (min-colors 89)) (:inverse-video t :background "#839496" :foreground "#002b36"))))
 '(fixed-pitch ((t (:family "JetBrains Mono NL" :width normal :weight regular))))
 '(fixed-pitch-serif ((t (:family "Courier New" :width normal :weight regular))))
 '(variable-pitch ((t (:family "Noto Sans" :width normal :weight regular))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#073642"))))
 '(region ((t (:extend t :foreground "selectedTextColor" :background "selectedTextBackgroundColor"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#073642" :extend t))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:slant normal :weight bold :foreground "#839496"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:slant normal :foreground "#586e75"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:weight bold :foreground "#268bd2"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:slant normal :foreground "#2aa198"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:weight bold :foreground "#859900"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:weight bold :foreground "#b58900"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold :foreground "#859900"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold :foreground "#b58900"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((((class color) (min-colors 89)) (:weight bold :underline (:color foreground-color :style line) :foreground "#b58900"))))
 '(link-visited ((((class color) (min-colors 89)) (:weight normal :underline (:color foreground-color :style line) :foreground "#b58900"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#002b36" :foreground "#586e75"))))
 '(header-line ((((class color) (min-colors 89)) (:box (:line-width (2 . 2) :color "#002b36" :style unspecified) :background "#002b36" :foreground "#839496" :underline (:color "#073642" :style line) :overline nil :inverse-video unspecified))))
 '(tooltip ((t (:foreground "#93a1a1" :background "#073642"))))
 '(mode-line ((t (:underline nil :overline "#284b54" :box nil :foreground "#839496" :background "#073642"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :foreground "#93a1a1"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:underline nil :overline "#284b54" :box nil :foreground "#586e75" :background "#002b36"))))
 '(isearch ((((class color) (min-colors 89)) (:weight normal :background "#d33682" :foreground "#002b36"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:bold t :background "#002b36" :foreground "#dc322f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:weight normal :background "#b58900" :foreground "#002b36"))))
 '(match ((((class color) (min-colors 89)) (:weight bold :foreground "#93a1a1" :background "#073642"))))
 '(next-error ((((class color) (min-colors 89)) (:weight normal :background "#4c2942" :foreground "#c47896"))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'bootstrap)
