(deftheme bootstrap
  "Created 2024-10-25.")

(custom-theme-set-faces
 'bootstrap
 '(default ((t (:family "JetBrains Mono NL" :foundry "nil" :width normal :height 120 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#ffffff" :background "#0d0e1c" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#ff66ff"))))
 '(fixed-pitch ((t (:family "JetBrains Mono NL" :width normal :weight regular))))
 '(variable-pitch ((t (:family "SF Pro" :width normal :weight regular))))
 '(escape-glyph ((t (:foreground "#ff5f59"))))
 '(homoglyph ((t (:foreground "#fec43f"))))
 '(minibuffer-prompt ((t (:inherit (modus-themes-prompt)))))
 '(highlight ((t (:foreground "#ffffff" :background "#45605e"))))
 '(region ((t (:extend t :foreground "#ffffff" :background "#555a66"))))
 '(shadow ((t (:foreground "#989898"))))
 '(secondary-selection ((t (:extend t :foreground "#ffffff" :background "#654a39"))))
 '(trailing-whitespace ((t (:background "#9d1f1f"))))
 '(font-lock-bracket-face ((t (:foreground "#ffffff"))))
 '(font-lock-builtin-face ((t (:foreground "#f78fe7" :inherit (modus-themes-bold)))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#ff9f80" :inherit (modus-themes-slant)))))
 '(font-lock-constant-face ((t (:foreground "#00bcff"))))
 '(font-lock-delimiter-face ((t (:foreground "#ffffff"))))
 '(font-lock-doc-face ((t (:foreground "#9ac8e0" :inherit (modus-themes-slant)))))
 '(font-lock-doc-markup-face ((t (:foreground "#caa6df" :inherit (modus-themes-slant)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#feacd0"))))
 '(font-lock-keyword-face ((t (:foreground "#b6a0ff" :inherit (modus-themes-bold)))))
 '(font-lock-negation-char-face ((t (:inherit (error)))))
 '(font-lock-number-face ((t (:foreground "#ffffff"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t (:foreground "#ffffff"))))
 '(font-lock-preprocessor-face ((t (:foreground "#ff7f86"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t (:foreground "#ffffff"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#feacd0" :inherit (modus-themes-bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#00c06f" :inherit (modus-themes-bold)))))
 '(font-lock-string-face ((t (:foreground "#70b900"))))
 '(font-lock-type-face ((t (:foreground "#6ae4b9" :inherit (modus-themes-bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#00d3d0"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#fec43f" :inherit (modus-themes-bold)))))
 '(button ((t (:underline (:color "#79a8ff" :style line :position nil) :foreground "#79a8ff"))))
 '(link ((t (:inherit (button)))))
 '(link-visited ((t (:underline (:color "#feacd0" :style line :position nil) :foreground "#feacd0"))))
 '(fringe ((t (:foreground "#ffffff"))))
 '(header-line ((t (:background "#1d2235" :inherit (modus-themes-ui-variable-pitch)))))
 '(tooltip ((((class color) (min-colors 256)) (:inherit (modus-themes-ui-variable-pitch) :foreground "#ffffff" :background "#4a4f69"))))
 '(mode-line ((((class color) (min-colors 256)) (:foreground "#ffffff" :background "#484d67" :overline "#979797" :box (:line-width (1 . 1) :color nil :style nil) :inherit (modus-themes-ui-variable-pitch)))))
 '(mode-line-buffer-id ((t (:inherit (bold)))))
 '(mode-line-emphasis ((t (:foreground "#9fefff" :inherit (bold)))))
 '(mode-line-highlight ((((class color) (min-colors 256)) (:box (:line-width (1 . 1) :color nil :style nil) :foreground "#ffffff" :background "#45605e"))))
 '(mode-line-inactive ((((class color) (min-colors 256)) (:foreground "#969696" :background "#292d48" :overline "#606270" :box (:line-width (1 . 1) :color nil :style nil) :inherit (modus-themes-ui-variable-pitch)))))
 '(isearch ((t (:inherit (modus-themes-search-current)))))
 '(isearch-fail ((t (:inherit (modus-themes-prominent-error)))))
 '(lazy-highlight ((t (:inherit (modus-themes-search-lazy)))))
 '(match ((t (:foreground "#ffffff" :background "#552f5f"))))
 '(next-error ((t (:extend t :inherit (modus-themes-prominent-error)))))
 '(query-replace ((t (:inherit (modus-themes-search-replace))))))

(provide-theme 'bootstrap)
